### ISSUE TITLE
Tests which are failed in OneTimeSetup are not open in Report Portal

### ISSUE THREAD

**Issue by vitali-sonchyk-epam** [reportportal/example-net-nunit#6] opened 2018-10-05 11:13 UTC
Environment:
nUnit Framework version- 3.10.1
nunit console runner - 3.9.0
ReportPortal.Nunit - 3.3.10
ReportPortal.Client - 2.1.0
ReportPortal.Shared - 2.0.6

ReportPortal instance version: Build: 4.2.2

Steps:
1. Create any Test class with the OneTimeSetUp and any amount of tests(eg: 5)
2. Add throwing any exception in OneTimeSetUp
3. Run the test class (--where "class = namespace.classname")

Expected: the report portal should display all 5 failures.
Actual: only one failure is displayed. After attempt to open it an error is displayed in the bottom:
Link to test-item become invalid. Test-item was restored by id from server.

Note: An exception is displayed in nUnit output. Please see full nUnit output

[RPoutput.txt](https://github.com/reportportal/example-net-nunit/files/2450033/RPoutput.txt)

**Comment by nvborisenko** [comment] 2018-10-05 19:18
Cannot reproduce.

![untitled](https://user-images.githubusercontent.com/22616990/46555340-a40d3980-c8eb-11e8-975d-b6a5e5cf5849.png)

This is definitely the issue in nunit plugin, we need reproduce it to fix. Please share very simple project.

**Comment by nvborisenko** [comment] 2018-10-05 19:33
Reproduced using [SetUpFixture] attribute. Thank you.

Created new issue in correct repository: https://github.com/reportportal/agent-net-nunit/issues/23, closing this one.

**Closed as completed** 2018-10-05 19:34 UTC
